#Параметры логгера, см пример logger_ex или файлы mlogger.*

[Logger]
mmax=100
fsize=100000
fpath=
fnum=3
level=INFO
stime=10000

#Общие настройки программы

[Settings]
#Интервал таймера, выводящего сообщения на экран и в лог файл
interval=100

#Здесь определим количество групп чисел, по которым будет отрабатывать программа. Можно менять

[Groups]
group1=XXL
group2=Large
group3=Medium
group4=Small

#А теперь установим параметры для всех групп чисел из группы Groups. В них будет стандартный набор ключей

[XXL]
min=100000
#заведомо больше диапазона библиотеки to_words. Будем получать соотв. сообщения
max=1200001
count=50

[Large]
min=1000
max=100000
count=50

[Medium]
min=100
max=1000
count=50

[Small]
min=0
max=100
count=50
